name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [11, 17]
        browser: [chrome, firefox]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      if: matrix.browser == 'chrome'
    
    - name: Install Firefox
      uses: browser-actions/setup-firefox@latest
      if: matrix.browser == 'firefox'
    
    - name: Run tests
      run: mvn clean test -Dbrowser=${{ matrix.browser }}
    
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports-${{ matrix.java }}-${{ matrix.browser }}
        path: |
          target/surefire-reports/
          output/screenshots/
    
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results (${{ matrix.java }}-${{ matrix.browser }})
        path: target/surefire-reports/*.xml
        reporter: java-junit